testing final .yml config and whehter or not it crashes

diff --git a/.github/workflows/doc_build.yml b/.github/workflows/doc_build.yml
--- a/.github/workflows/doc_build.yml
+++ b/.github/workflows/doc_build.yml
@@ -30,7 +30,7 @@ jobs:
       run: |
         find . -iname '*.ipynb' -exec jupyter nbconvert --to notebook --inplace --execute {} \;  > out.txt 2>&1
         cat out.txt
-        cat out.txt | grep -zvqi error && echo 'no' || exit
+        cat out.txt | grep -zvqi exception && echo 'no errors detected' || exit
     - name: Make the docs
       run: |
         cd docssrc && make github
